version: '3'
volumes:
  bundle:
    driver: 'local'
  bundle_install:
    driver: 'local'
  log:
    driver: 'local'
  elasticsearch-data:
    driver: 'local'
  postgresql-data:
    driver: 'local'
services:
  elasticsearch:
    build: ./docker-development/elasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    environment:
      - xpack.security.enabled=false
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - default
  postgresql:
    image: postgres:10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - default
  app:
    build: ./docker-development/app
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      MEMCACHE_SERVERS: memcached
    volumes:
      - .:/app
      - bundle:/app/.bundle
      - bundle_install:/app/vendor/bundle
      - log:/app/log
    ports:
      - 3000:3000
    networks:
      - default
    depends_on:
      - elasticsearch
      - postgresql
