# 開発環境用Elasticsearch
# 公式のもの + プラグインインストール

FROM docker.elastic.co/elasticsearch/elasticsearch:5.6.5
MAINTAINER Yuichi Takeuchi <yuichi.takeuchi@takeyuweb.co.jp> (@takeyuweb)

RUN elasticsearch-plugin install analysis-kuromoji
